### ISSUE TITLE
[Bug]: "Ethernet is not a recognized network service."

### ISSUE THREAD

**Issue by vitorgalvao** [chrisgrieser/alfred-atop#3]
### Bug Description

When running the new `dns` keyword, it errors out and shows no results.

```
…/atop.de.chris-grieser.atop/scripts/select-dns-server.js: execution error: Error: Error: Ethernet is not a recognized network service.
** Error: The parameters were not valid. (4)
```

I’m connected via Wi-Fi but cabled connection is a possibility.

### To Reproduce

Run `dns` or `atop` then pick DNS from the list.

### macOS Version

macOS 13.5

### Device Model

MacBook Air, M1, 2020

### Debugging Log

```Text
…/atop.de.chris-grieser.atop/scripts/select-dns-server.js: execution error: Error: Error: Ethernet is not a recognized network service.
** Error: The parameters were not valid. (4)
```

### Workflow Configuration

Not applicable. Settings were not modified, this is a fresh installation.

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/alfred-atop/releases/latest) of this workflow.
- [X] I am using Alfred 5. (Older versions are not supported anymore.)

**Comment by chrisgrieser** [comment]
Huh, and here I thought "Ethernet" and "Wi-fi" were static network targets. But in fact, they are just dynamic names.

Fixed in 1.1.3.

Fixed another edge case in 1.1.4
