### ISSUE TITLE
Feature Request: New Screenshots for DNS

### ISSUE THREAD

**Issue by vitorgalvao** [chrisgrieser/alfred-atop#4]
### Feature Requested

The README doesn’t have a screenshot for the DNS feature. Plus the top screenshot (`atop`) doesn’t include it. This is relevant to updating the Gallery as well.

Tangentially, would you mind resharing your theme? I think you may have done some modifications since the last time you shared it as the screenshots I took don’t align exactly.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
done. will submit a gallery edit with the images and my theme in a moment
