### ISSUE TITLE
[Bug]: display tmux process instead of zsh

### ISSUE THREAD

**Issue by timtyrrell** [chrisgrieser/alfred-atop#5]
### Bug Description

I am curious how to view the tmux process specifically, like I can in Activity Manager. When I search for `tmux` I see the zsh sessions that are open in tmux sessions.

### Relevant Screenshot

<img width="714" alt="Screenshot 2024-02-07 at 7 40 32 AM" src="https://github.com/chrisgrieser/alfred-atop/assets/100535/af7d7fcd-f18d-4df0-9240-bd630c431527">

<img width="897" alt="Screenshot 2024-02-07 at 7 41 42 AM" src="https://github.com/chrisgrieser/alfred-atop/assets/100535/ad83e0f1-fcae-45c9-96dd-4004221ffdc3">

### macOS Version

macOS 14.3

### Device Model

Apple M1 Pro

### Debugging Log

```Text
This didn't seem to work for me?
```

### Workflow Configuration

I made no changes.

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/alfred-atop/releases/latest) of this workflow.
- [X] I am using Alfred 5. (Older versions are not supported anymore.)

**Comment by chrisgrieser** [comment]
that actually isn't implemented, but it's a good idea. I added the ability to search for parent processes by appending "parent" to the query, so in your case, you'd search for "parent tmux".
(might take a few days before it's available in the Alfred Gallery, you can download it beforehand here: 
https://github.com/chrisgrieser/alfred-atop/releases/download/1.2.0/alfred-atop.alfredworkflow)

**Comment by timtyrrell** [comment]
Thanks, I will wait for the gallery update and try it out

**Comment by timtyrrell** [comment]
Alfred Gallery finally was the update. Looks good, thanks!

<img width="716" alt="Screenshot 2024-02-12 at 8 47 30 AM" src="https://github.com/chrisgrieser/alfred-atop/assets/100535/3deadbe4-bbff-49d4-88ff-e2223211c00b">
