### ISSUE TITLE
Feature Request: More Details within Readme File

### ISSUE THREAD

**Issue by pictosun** [chrisgrieser/alfred-atop#7]
### Feature Requested

Hi,

I'm using atop since a few days now, but sometimes I don't really know all those logos and infos mean.

Sadly I cannot find any explanation.

Enclosed a screenshot explaning the things I mean.

Hope you can help?
<img width="114" alt="SCR-20240311-oqxl" src="https://github.com/chrisgrieser/alfred-atop/assets/55917962/296a7a37-e91b-4bd5-9dd3-8f7bc2adb6e2">

![SCR-20240311-orhz](https://github.com/chrisgrieser/alfred-atop/assets/55917962/a6321bfb-3ca5-47e0-af9f-e9ac5c07c814)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
good call, added explanations to the readme.
